### ISSUE TITLE
incorrect RFM70 module initialization

### ISSUE THREAD

**Issue by antongus** [KonstantinChizhov/Mcucpp#7]
RFM70 datasheet claims that only registers 0..8 from bank 1 should be written most significant byte first (MSB first).
`Rfm70<>::WriteReg32()` function writes 32-bit data in platform native endianess (little endian for AVR and STM32, not sure for MSP430). It means that `Rfm70<>::WriteReg32()` sends least significant byte of 32-bit word first.
But `Rfm70<>::InitBank1Regs()` assumes MSB first for WriteReg32(): "magic" register values from sample code for regs 0..6 are sent as-is, and only reg values for regs 0x0c and 0x0d send in reverse byte order. 
Also SetAddresess() depends on WriteReg32() function and sets address incorrectly.

**Comment by KonstantinChizhov** [comment]
Thanks for information.

**Comment by antongus** [comment]
Sorry, I was wrong. I checked the sample code again, and discovered that they send regs 0..8 of bank 1 LSB first, and all other regs MSB first. So it seems to be they just reversed all the initialization values. Therefore your code works exactly like the sample code.
Only issue remaining - SetAddress() function swaps 4 first bytes of address. It is not a problem, if both sides uses your library.
